version: '3.8'

services:
  kimi-k2:
    build: .
    container_name: kimi-k2-server
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - HF_HOME=/app/models
      - TRANSFORMERS_CACHE=/app/models
      - MODEL_NAME=moonshot-ai/kimi-k2-instruct
      - MAX_MODEL_LEN=32768
      - TENSOR_PARALLEL_SIZE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - kimi-network

  # Optional: Nginx reverse proxy for production use
  nginx:
    image: nginx:alpine
    container_name: kimi-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - kimi-k2
    networks:
      - kimi-network
    restart: unless-stopped

networks:
  kimi-network:
    driver: bridge